### ISSUE TITLE
Feature Request: JSON Feed support

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-feed#10]
Would be awesome if Zend Feed supported parsing [JSON feeds](https://jsonfeed.org/). Publishing and parsing them is much more straightforward and lightweight compared to RSS and Atom, and adoption is starting to pick up.

---

Originally posted by @brandonkelly at https://github.com/zendframework/zend-feed/issues/42

**Comment by weierophinney** [comment]
It would be good, but I'm very wary of a month old standard which all but states that Version 1 may be the only version ever needed. Talk about hubris... The problem with these random drop standards, regardless of who writes them, is their isolation/lack of feedback during development. The issue tracker is littered with basic questions, improvements and problems that seem to firmly point to a Version 2 being needed sooner rather than later.

That said, all wariness aside, it should be relatively easy to add but I would expect support to need an overhaul in time to remain relevant. The spec and Atom/RSS mappings also needs a close reading, and it may be prone to disruption if a major JSONFeed publisher starts hacking in some customisations.

Then again, isn't that all new stuff in a nutshell? :)





---

Originally posted by @padraic at https://github.com/zendframework/zend-feed/issues/42#issuecomment-308387623

**Comment by weierophinney** [comment]
I think major feedreader support it : feebin.com, inoreader.com etc. not sure how much work needed, but will be great if we add json feed support. 

---

Originally posted by @rajjanorkar at https://github.com/zendframework/zend-feed/issues/42#issuecomment-336831837

**Comment by froschdesign** [comment]
The problem so far has been that there was no schema which can be used for validation. But now there are schemas for version 1.0 and [1.1](https://www.jsonfeed.org/2020/08/07/json-feed-version.html) of "JSON Feed": https://github.com/sonicdoe/jsonfeed-schema

I already created a prototype for reading a JSON feed but for the writing part we need to split the `Laminas\Feed\Writer\Renderer\RendererInterface` because it's based on XML output:

https://github.com/laminas/laminas-feed/blob/254bfabeac599a704bc0aa798a961fcfa7a1c127/src/Writer/Renderer/RendererInterface.php#L23-L42

**Comment by dvikan** [comment]
+1

**Comment by rajpt** [comment]
+1

**Comment by Ocramius** [comment]
Ah yep, closing+locking until I see real traction on that spec.
