### ISSUE TITLE
DOMDocument::loadXML(): CData section too big found

### ISSUE THREAD

**Issue by poison-zer0** [laminas/laminas-feed#86]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  |  2.22.0

#### Summary

If data of more than 10 MB is passed to `setContent()` with `<![CDATA[{$content}]]>`, we get CData section too big error. 

Please note that `CDATA` is still not being passed to the `setContent()` as mentioned [here.](https://github.com/laminas/laminas-feed/issues/7)

#### Current behavior

Error is being thrown and execution stops at `loadXML()` located in `Writer/Renderer/Entry/Atom.php`.

#### How to reproduce

The following is in PHP:

While creating the feed, simply call the below function inside`setContent()`

```
private function getCdataFromContent(?string $content = ''): string
    {
        $content = str_repeat('This is a large text. ', 1000000); // Creates a large string over 10MB
        return "<![CDATA[{$content}]]>";
    }
```

#### Expected behavior

XML should be generated for files larger than 10MB.

**Comment by froschdesign** [comment]
The [`XML_PARSE_HUGE` flag](https://www.php.net/manual/libxml.constants.php#constant.libxml-parsehuge) as option for [`DOMDocument::loadXML`](https://www.php.net/manual/domdocument.loadxml.php) can help here, but this could lead to problems on the consumer side, because it is not certain if a parser can process the huge file.
What do you put in a feed that is this big?

**Comment by poison-zer0** [comment]
It's basically a feed produced by the client who's content exceeds 10 million characters, which is why we need to have `XML_PARSH_HUGE` flag for `loadXML()`. Can it be put as an optional argument in the package?

**Comment by froschdesign** [comment]
> Can it be put as an optional argument in the package?

No, because a size of 10 MB for a feed does not correspond to a regular usage and possible problems on the consumer side.

But you can extend the relevant classes for your use case:

https://github.com/laminas/laminas-feed/blob/669792b819fca7274698147ad7a2ecc1b0a9b141/src/Writer/Renderer/Feed/Atom.php#L63-L65

Then render the feed with your custom feed and entry classes:

```php
$renderer = new MyCustom\Feed\Atom($feed);
$renderer->setType('atom');
$xml = $renderer->render()->saveXml();
```

**Comment by poison-zer0** [comment]
Oh ok, thought it might have been a bug. Then the only solution would be to extend the class. Thanks anyways!
